In [ ]:
import importlib
from hcdp import hcdp
importlib.reload(hcdp)
import numpy as np

# test = hcdp.FileDownloadAPI('rainfall', year=2020, month=4)
# dataset = test.get_data()
# test.plot_raster()


# getting data for a full year

In [50]:
import importlib
from hcdp import hcdp
importlib.reload(hcdp)
import numpy as np

product_type = 'rainfall'
year = '2020'


mean_values = []  # to store cummulative mean

for month in range(1, 13):
    test = hcdp.FileDownloadAPI('rainfall', year=year, month=month)
    dataset = test.get_data()

     
    band1 = dataset.read(1)
        
    # Compute the mean of band 1
    mean_band1 = np.mean(band1)
    
    # Store the mean value
    mean_values.append(mean_band1)
    

if mean_raster is not None:
    mean_raster /= 12  # Divide by 12 to get the mean

    # Now, mean_raster contains the average for the year (2020).
    # You can save it as a new raster if required, or visualize it using matplotlib
    print(f"Mean raster for {year} computed successfully.")
else:
    print("Failed to compute mean raster for the year.")

hcdp.plot_raster_band(mean_raster)

c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ikeauth.its.hawaii.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\numpy\_core\_methods.py:127: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ikeauth.its.hawaii.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\urllib3\connectionpool.py:

ValueError: day is out of range for month

In [17]:
dataset.read(1)

array([[-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38],
       [-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38],
       [-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38],
       ...,
       [-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38],
       [-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38],
       [-3.4e+38, -3.4e+38, -3.4e+38, ..., -3.4e+38, -3.4e+38, -3.4e+38]],
      dtype=float32)

In [16]:
np.unique(dataset.read(1))

array([-3.4000000e+38,  2.0339863e+01,  2.0370369e+01, ...,
        9.6138696e+02,  9.6307141e+02,  9.9695148e+02], dtype=float32)

In [10]:
import numpy as np
np.unique(dataset.read(1))

array([-3.4000000e+38,  2.0339863e+01,  2.0370369e+01, ...,
        9.6138696e+02,  9.6307141e+02,  9.9695148e+02], dtype=float32)

In [2]:
import requests

def download_rainfall_data(production, period, extent, fill, filetype, year, month, day=None, output_filename='rainfall_data'):
    base_url = "https://ikeauth.its.hawaii.edu/files/v2/download/public/system/ikewai-annotated-data/HCDP/production/rainfall"
    
    # Construct the URL
    url = f"{base_url}/{production}/{period}/{extent}/{fill}/{filetype}/{year}/{month}/rainfall_{production}_{period}_{extent}_{fill}_{filetype}_{year}_{month}"
    
    if day:
        url += f"_{day}"
    
    url += f".{filetype}"
    
    # Send the GET request (no authentication required)
    response = requests.get(url, verify=False)  # verify=False if you want to ignore SSL verification
    
    if response.status_code == 200:
        # Save the content to a file
        with open(output_filename, 'wb') as f:
            f.write(response.content)
        print(f"Data downloaded successfully: {output_filename}")
    else:
        print(f"Failed to download data. HTTP Status code: {response.status_code}")

# Example usage
download_rainfall_data(
    production="new",
    period="month",
    extent="statewide",
    fill="partial",
    filetype="tif",
    year="2012",
    month="03",
    day=None,  # Optional
    output_filename="rainfall_data_2012_03.tif"
)


c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ikeauth.its.hawaii.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


Failed to download data. HTTP Status code: 404


In [3]:
import requests

def download_rainfall_file(url, output_filename):
    # Send the GET request to download the file
    response = requests.get(url, verify=False)  # verify=False if you want to ignore SSL verification
    
    if response.status_code == 200:
        # Save the file content to the specified output filename
        with open(output_filename, 'wb') as file:
            file.write(response.content)
        print(f"File downloaded successfully: {output_filename}")
    else:
        print(f"Failed to download file. HTTP Status code: {response.status_code}")

# Example: Construct the URL and download the file
url = "https://ikeauth.its.hawaii.edu/files/v2/download/public/system/ikewai-annotated-data/HCDP/production/rainfall/new/month/statewide/data_map/2012/rainfall_new_month_statewide_data_map_2012_03.tif"
output_filename = "rf_test.tif"

download_rainfall_file(url, output_filename)


c:\Users\jnicolow\AppData\Local\anaconda3\envs\genv\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ikeauth.its.hawaii.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


File downloaded successfully: rf_test.tif
